/**
 * Application Form API
 * API Task
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationFormAttributes } from '../models/ApplicationFormAttributes';
import { HttpFile } from '../http/http';

export class ApplicationFOrmData {
    'id': string;
    'type': string;
    'attributes': ApplicationFormAttributes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "ApplicationFormAttributes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationFOrmData.attributeTypeMap;
    }

    public constructor() {
    }
}

