/**
 * Application Form API
 * API Task
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProfileTemplate } from '../models/ProfileTemplate';
import { QuestionTemplate } from '../models/QuestionTemplate';
import { HttpFile } from '../http/http';

export class ApplicationFormAttributesProfile {
    'education': ProfileTemplate;
    'experience': ProfileTemplate;
    'resume': ProfileTemplate;
    'profileQuestions'?: Array<QuestionTemplate>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "education",
            "baseName": "education",
            "type": "ProfileTemplate",
            "format": ""
        },
        {
            "name": "experience",
            "baseName": "experience",
            "type": "ProfileTemplate",
            "format": ""
        },
        {
            "name": "resume",
            "baseName": "resume",
            "type": "ProfileTemplate",
            "format": ""
        },
        {
            "name": "profileQuestions",
            "baseName": "profileQuestions",
            "type": "Array<QuestionTemplate>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationFormAttributesProfile.attributeTypeMap;
    }

    public constructor() {
    }
}

