/**
 * Application Form API
 * API Task
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationFOrmData } from '../models/ApplicationFOrmData';
import { HttpFile } from '../http/http';

export class ApplicationFOrm {
    'data': ApplicationFOrmData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "ApplicationFOrmData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationFOrm.attributeTypeMap;
    }

    public constructor() {
    }
}

