/**
 * Application Form API
 * API Task
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class QuestionTemplate {
    'id'?: string;
    'type': QuestionTemplateTypeEnum;
    'question': string;
    'choices'?: Array<string>;
    'maxChoice'?: number;
    'disqualify'?: boolean;
    'other'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "QuestionTemplateTypeEnum",
            "format": ""
        },
        {
            "name": "question",
            "baseName": "question",
            "type": "string",
            "format": ""
        },
        {
            "name": "choices",
            "baseName": "choices",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "maxChoice",
            "baseName": "maxChoice",
            "type": "number",
            "format": ""
        },
        {
            "name": "disqualify",
            "baseName": "disqualify",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "other",
            "baseName": "other",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuestionTemplate.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum QuestionTemplateTypeEnum {
    Paragraph = 'Paragraph',
    ShortAnswer = 'ShortAnswer',
    YesNo = 'YesNo',
    Dropdown = 'Dropdown',
    MultipleChoice = 'MultipleChoice',
    Date = 'Date',
    Number = 'Number',
    FileUpload = 'FileUpload'
}

